# 서론

### 1. 전 세계에서 발생한 지진 현황

<태블로에서 세계지도에 발생한 지진들을 표시하여 시각화>

지진은 판의 충돌, 지각의 변형, 화산 활동, 지하수 침반, 태풍으로 인한 지하수 수위 상승과 같은 원인 이외에도 인간의 지반 공사, 핵실험 등 다양한 이유로 발생하고 있습니다. 지진이 위험한 이유는 대규모 지반진동 뿐만 아니라 해일 동반, 낙상사고, 여진 등으로 인류에게 막대한 피해를 끼치기 때문입니다.

비교적 최근인 2004년 푸켓의 지진해일, 2005년 카슈미르 지진, 2008년 쓰촨성 지진, 2010년 아이티 지진,2011년에 일어난 일본 지진해일은 인류에게 막대한 피해를 주었습니다. 뿐만 아니라 2011년에 일어난 일본 지진해일을 통해서 원자력 발전소의 붕괴와 같은 대참사를 통해 지진의 위험성에 대해서 체감할 수 있었습니다.

그렇다면 과연 우리가 살고 있는 대한민국은 지진의 위협으로 부터 안전할까?라는 의문이 들었고, 이러한 의문을 바탕으로 데이터 분석을 시작하였습니다.

### 2. 대한민국 국민들의 자연재해 인식 현황

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False

In [2]:
df_edu = pd.read_excel('..\찐최종 데이터셋\대책현황\교육\국내자연재해_국민인식현황_찐최종.xlsx')
df_edu

,특성별(1),특성별(2),2008,2008.1,2008.2,2008.3,2008.4,2010,2010.1,2010.2,...,2020,2020.1,2020.2,2020.3,2020.4,2022,2022.1,2022.2,2022.3,2022.4
0,특성별(1),특성별(2),매우 안전,비교적 안전,보통,비교적 안전하지 않음,매우 안전하지 않음,매우 안전,비교적 안전,보통,...,매우 안전,비교적 안전,보통,비교적 안전하지 않음,매우 안전하지 않음,매우 안전,비교적 안전,보통,비교적 안전하지 않음,매우 안전하지 않음
1,전체,계,0.7,16.5,42.7,35.1,4.9,1,17.7,45.4,...,3.7,33.3,40.1,20.1,2.7,4.1,35.3,39.7,18.6,2.4
2,동·읍면부,동부,0.8,17.5,43.9,33.3,4.5,1.1,18.3,46.1,...,3.8,34.1,39.9,19.4,2.7,4.1,35.7,39.8,18.1,2.2
3,동·읍면부,읍면부,0.6,12.5,37.4,43,6.5,0.9,15.3,42.2,...,3.4,29.3,41.1,23.6,2.6,3.9,33.5,38.8,20.8,3
4,성별,남자,1,18.3,43.1,33,4.6,1.3,20,45.8,...,4.9,36.5,38.9,17.5,2.3,5.2,37.5,39,16.4,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,연령*교육정도,60세 이상*고졸,0.9,17.3,38.5,37.7,5.7,1.4,16.8,44.4,...,2.1,26.4,40.3,27.5,3.6,2.4,29,41,25,2.7
95,연령*교육정도,60세 이상*대졸이상,0.7,17.8,47.5,29.9,4.1,1.8,24.3,44.6,...,3.1,31.3,37.9,23.8,3.9,2.8,34,40.6,20.6,2.1
96,연령*교육정도,65세 이상*중졸이하,0.7,13.8,40.3,40,5.2,1.2,14.8,43.8,...,3,25.2,39.8,28.7,3.3,3,30.7,38.8,24.4,3.1
97,연령*교육정도,65세 이상*고졸,0.7,17.6,38,37.9,5.8,1.2,16.3,45.6,...,2.2,28.1,38.5,27.9,3.3,2.6,29.3,39.5,26,2.6
98,연령*교육정도,65세 이상*대졸이상,1.2,18.4,46.9,29.6,3.9,2.2,24.7,42.5,...,3.4,29.7,39.8,23.9,3.2,3.2,33.4,39,21.8,2.7

In [3]:
df_edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 42 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   특성별(1)  99 non-null     object
 1   특성별(2)  99 non-null     object
 2   2008    99 non-null     object
 3   2008.1  99 non-null     object
 4   2008.2  99 non-null     object
 5   2008.3  99 non-null     object
 6   2008.4  99 non-null     object
 7   2010    99 non-null     object
 8   2010.1  99 non-null     object
 9   2010.2  99 non-null     object
 10  2010.3  99 non-null     object
 11  2010.4  99 non-null     object
 12  2012    99 non-null     object
 13  2012.1  99 non-null     object
 14  2012.2  99 non-null     object
 15  2012.3  99 non-null     object
 16  2012.4  99 non-null     object
 17  2014    99 non-null     object
 18  2014.1  99 non-null     object
 19  2014.2  99 non-null     object
 20  2014.3  99 non-null     object
 21  2014.4  99 non-null     object
 22  2016    99 non-null     object
 23  2016.1  99 non-null     object
 24  2016.2  99 non-null     object
 25  2016.3  99 non-null     object
 26  2016.4  99 non-null     object
 27  2018    99 non-null     object
 28  2018.1  99 non-null     object
 29  2018.2  99 non-null     object
 30  2018.3  99 non-null     object
 31  2018.4  99 non-null     object
 32  2020    99 non-null     object
 33  2020.1  99 non-null     object
 34  2020.2  99 non-null     object
 35  2020.3  99 non-null     object
 36  2020.4  99 non-null     object
 37  2022    99 non-null     object
 38  2022.1  99 non-null     object
 39  2022.2  99 non-null     object
 40  2022.3  99 non-null     object
 41  2022.4  99 non-null     object
dtypes: object(42)
memory usage: 32.6+ KB